name: SSS Ancillary CI

on:
  push:
    tags: ["*"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Publish
        run: sbt test publish